/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as S3ChineseIndexRouteImport } from './routes/s3/chinese/index'
import { Route as S3MathPercentageIndexRouteImport } from './routes/s3/math/percentage/index'
import { Route as S3MathFractionIndexRouteImport } from './routes/s3/math/fraction/index'
import { Route as S3MathDecimalIndexRouteImport } from './routes/s3/math/decimal/index'
import { Route as S3ChineseYibiandiaoIndexRouteImport } from './routes/s3/chinese/yibiandiao/index'
import { Route as S3ChineseShengciIndexRouteImport } from './routes/s3/chinese/shengci/index'
import { Route as S3ChineseChoubeiIndexRouteImport } from './routes/s3/chinese/choubei/index'
import { Route as S3MathFractionClawMachineIndexRouteImport } from './routes/s3/math/fraction/claw-machine/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const S3ChineseIndexRoute = S3ChineseIndexRouteImport.update({
  id: '/s3/chinese/',
  path: '/s3/chinese/',
  getParentRoute: () => rootRouteImport,
} as any)
const S3MathPercentageIndexRoute = S3MathPercentageIndexRouteImport.update({
  id: '/s3/math/percentage/',
  path: '/s3/math/percentage/',
  getParentRoute: () => rootRouteImport,
} as any)
const S3MathFractionIndexRoute = S3MathFractionIndexRouteImport.update({
  id: '/s3/math/fraction/',
  path: '/s3/math/fraction/',
  getParentRoute: () => rootRouteImport,
} as any)
const S3MathDecimalIndexRoute = S3MathDecimalIndexRouteImport.update({
  id: '/s3/math/decimal/',
  path: '/s3/math/decimal/',
  getParentRoute: () => rootRouteImport,
} as any)
const S3ChineseYibiandiaoIndexRoute =
  S3ChineseYibiandiaoIndexRouteImport.update({
    id: '/s3/chinese/yibiandiao/',
    path: '/s3/chinese/yibiandiao/',
    getParentRoute: () => rootRouteImport,
  } as any)
const S3ChineseShengciIndexRoute = S3ChineseShengciIndexRouteImport.update({
  id: '/s3/chinese/shengci/',
  path: '/s3/chinese/shengci/',
  getParentRoute: () => rootRouteImport,
} as any)
const S3ChineseChoubeiIndexRoute = S3ChineseChoubeiIndexRouteImport.update({
  id: '/s3/chinese/choubei/',
  path: '/s3/chinese/choubei/',
  getParentRoute: () => rootRouteImport,
} as any)
const S3MathFractionClawMachineIndexRoute =
  S3MathFractionClawMachineIndexRouteImport.update({
    id: '/s3/math/fraction/claw-machine/',
    path: '/s3/math/fraction/claw-machine/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/s3/chinese/': typeof S3ChineseIndexRoute
  '/s3/chinese/choubei/': typeof S3ChineseChoubeiIndexRoute
  '/s3/chinese/shengci/': typeof S3ChineseShengciIndexRoute
  '/s3/chinese/yibiandiao/': typeof S3ChineseYibiandiaoIndexRoute
  '/s3/math/decimal/': typeof S3MathDecimalIndexRoute
  '/s3/math/fraction/': typeof S3MathFractionIndexRoute
  '/s3/math/percentage/': typeof S3MathPercentageIndexRoute
  '/s3/math/fraction/claw-machine/': typeof S3MathFractionClawMachineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/s3/chinese': typeof S3ChineseIndexRoute
  '/s3/chinese/choubei': typeof S3ChineseChoubeiIndexRoute
  '/s3/chinese/shengci': typeof S3ChineseShengciIndexRoute
  '/s3/chinese/yibiandiao': typeof S3ChineseYibiandiaoIndexRoute
  '/s3/math/decimal': typeof S3MathDecimalIndexRoute
  '/s3/math/fraction': typeof S3MathFractionIndexRoute
  '/s3/math/percentage': typeof S3MathPercentageIndexRoute
  '/s3/math/fraction/claw-machine': typeof S3MathFractionClawMachineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/s3/chinese/': typeof S3ChineseIndexRoute
  '/s3/chinese/choubei/': typeof S3ChineseChoubeiIndexRoute
  '/s3/chinese/shengci/': typeof S3ChineseShengciIndexRoute
  '/s3/chinese/yibiandiao/': typeof S3ChineseYibiandiaoIndexRoute
  '/s3/math/decimal/': typeof S3MathDecimalIndexRoute
  '/s3/math/fraction/': typeof S3MathFractionIndexRoute
  '/s3/math/percentage/': typeof S3MathPercentageIndexRoute
  '/s3/math/fraction/claw-machine/': typeof S3MathFractionClawMachineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/s3/chinese/'
    | '/s3/chinese/choubei/'
    | '/s3/chinese/shengci/'
    | '/s3/chinese/yibiandiao/'
    | '/s3/math/decimal/'
    | '/s3/math/fraction/'
    | '/s3/math/percentage/'
    | '/s3/math/fraction/claw-machine/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/s3/chinese'
    | '/s3/chinese/choubei'
    | '/s3/chinese/shengci'
    | '/s3/chinese/yibiandiao'
    | '/s3/math/decimal'
    | '/s3/math/fraction'
    | '/s3/math/percentage'
    | '/s3/math/fraction/claw-machine'
  id:
    | '__root__'
    | '/'
    | '/s3/chinese/'
    | '/s3/chinese/choubei/'
    | '/s3/chinese/shengci/'
    | '/s3/chinese/yibiandiao/'
    | '/s3/math/decimal/'
    | '/s3/math/fraction/'
    | '/s3/math/percentage/'
    | '/s3/math/fraction/claw-machine/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  S3ChineseIndexRoute: typeof S3ChineseIndexRoute
  S3ChineseChoubeiIndexRoute: typeof S3ChineseChoubeiIndexRoute
  S3ChineseShengciIndexRoute: typeof S3ChineseShengciIndexRoute
  S3ChineseYibiandiaoIndexRoute: typeof S3ChineseYibiandiaoIndexRoute
  S3MathDecimalIndexRoute: typeof S3MathDecimalIndexRoute
  S3MathFractionIndexRoute: typeof S3MathFractionIndexRoute
  S3MathPercentageIndexRoute: typeof S3MathPercentageIndexRoute
  S3MathFractionClawMachineIndexRoute: typeof S3MathFractionClawMachineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s3/chinese/': {
      id: '/s3/chinese/'
      path: '/s3/chinese'
      fullPath: '/s3/chinese/'
      preLoaderRoute: typeof S3ChineseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s3/math/percentage/': {
      id: '/s3/math/percentage/'
      path: '/s3/math/percentage'
      fullPath: '/s3/math/percentage/'
      preLoaderRoute: typeof S3MathPercentageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s3/math/fraction/': {
      id: '/s3/math/fraction/'
      path: '/s3/math/fraction'
      fullPath: '/s3/math/fraction/'
      preLoaderRoute: typeof S3MathFractionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s3/math/decimal/': {
      id: '/s3/math/decimal/'
      path: '/s3/math/decimal'
      fullPath: '/s3/math/decimal/'
      preLoaderRoute: typeof S3MathDecimalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s3/chinese/yibiandiao/': {
      id: '/s3/chinese/yibiandiao/'
      path: '/s3/chinese/yibiandiao'
      fullPath: '/s3/chinese/yibiandiao/'
      preLoaderRoute: typeof S3ChineseYibiandiaoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s3/chinese/shengci/': {
      id: '/s3/chinese/shengci/'
      path: '/s3/chinese/shengci'
      fullPath: '/s3/chinese/shengci/'
      preLoaderRoute: typeof S3ChineseShengciIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s3/chinese/choubei/': {
      id: '/s3/chinese/choubei/'
      path: '/s3/chinese/choubei'
      fullPath: '/s3/chinese/choubei/'
      preLoaderRoute: typeof S3ChineseChoubeiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s3/math/fraction/claw-machine/': {
      id: '/s3/math/fraction/claw-machine/'
      path: '/s3/math/fraction/claw-machine'
      fullPath: '/s3/math/fraction/claw-machine/'
      preLoaderRoute: typeof S3MathFractionClawMachineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  S3ChineseIndexRoute: S3ChineseIndexRoute,
  S3ChineseChoubeiIndexRoute: S3ChineseChoubeiIndexRoute,
  S3ChineseShengciIndexRoute: S3ChineseShengciIndexRoute,
  S3ChineseYibiandiaoIndexRoute: S3ChineseYibiandiaoIndexRoute,
  S3MathDecimalIndexRoute: S3MathDecimalIndexRoute,
  S3MathFractionIndexRoute: S3MathFractionIndexRoute,
  S3MathPercentageIndexRoute: S3MathPercentageIndexRoute,
  S3MathFractionClawMachineIndexRoute: S3MathFractionClawMachineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
